version: '3.7'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: cc
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: epi_contacts_dev
    ports:
      - 5432:5432

  epi_contacts:
    build:
      args:
        OBAN_KEY: ${OBAN_KEY}
        UID: ${UID}
        USER: ${USER}
      context: docker
      target: local
    command: elixir --name server@epi_contacts --cookie foo -S mix phx.server
    depends_on:
      - postgres
    env_file: env.dev
    init: true
    ports:
      - 4000:4000
    volumes:
      - .:/epi-contacts:cached
      - epi_contacts_node_modules:/epi-contacts/assets/node_modules
      - epi_contacts_build:/epi-contacts/_build
      - epi_contacts_deps:/epi-contacts/deps

volumes:
  epi_contacts_build:
  epi_contacts_deps:
  epi_contacts_node_modules:
