version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: epi_contacts_dev
    ports:
      - 5432:5432
  epi_contacts:
    image: epi_contacts
    ports:
      - 4000:4000
    depends_on:
      - postgres
