version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: cc
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: epi_contacts_dev
    ports:
      - 5432:5432
  epi_contacts:
    build:
      args:
        OBAN_KEY: ${OBAN_KEY}
        UID: ${UID}
        USER: ${USER}
      context: docker
      target: local
    command: elixir --name server@epi_contacts --cookie foo -S mix phx.server
    # image: epi_contacts
    init: true
    ports:
      - 4000:4000
    environment:
      SECRETS: >
        {
          "COMMCARE_API_TOKEN": "COMMCARE_API_TOKEN_VALUE",
          "COMMCARE_USERNAME": "COMMCARE_USERNAME_VALUE",
          "COMMCARE_USER_ID": "COMMCARE_USER_ID_VALUE",
          "COMMCARE_BASIC_AUTH": "COMMCARE_BASIC_AUTH_VALUE",
          "BASIC_AUTH_USERNAME": "foo",
          "BASIC_AUTH_PASSWORD": "bar",
          "SECRET_KEY_BASE": "3TjNgvbwkybwa/wmAHz6kgakyAZ5ETIBCGuKRFW1s/ebkOqElLgtQrJrPZqY51cr",
          "LIVE_VIEW_SIGNING_SALT": "xbK8/I1ibfroHQvkZTMKbO7NOLAHtbdP",
          "RELEASE_LEVEL": "dev",
          "SENDGRID_API_KEY":"in-1Password",
          "SENDGRID_SENDER_ADDRESS":"no-reply@geometer.io",
          "SENTRY_CA_BUNDLE": "/opt/local/ssl/geometerCA.pem",
          "SENTRY_CA_BUNDLE_SOURCE": "xxxyyy"
        }
      DATABASE_SECRET: '{"password": "abc123", "dbname": "epi_contacts_dev",
        "engine": "postgres", "port": 5432, "host": "postgres", "username": "cc"}'
      DBSSL: "false"

    depends_on:
      - postgres

    volumes:
      - .:/epi-contacts:cached
      - epi_contacts_node_modules:/epi-contacts/assets/node_modules
      - epi_contacts_build:/epi-contacts/_build
      - epi_contacts_deps:/epi-contacts/deps

volumes:
  epi_contacts_build:
  epi_contacts_deps:
  epi_contacts_node_modules:
